### ISSUE TITLE
githubusercontent.com morphed to RawGit.com (dundalek.com)

### ISSUE THREAD

**Issue by fuhrmanator** [dundalek/GrammKit#21]
Hello,

When I enter https://raw.githubusercontent.com/fuhrmanator/GIFT-grammar-PEG.js/master/GIFT.pegjs as the grammar on dundalek.com/GrammKit it gets morphed to https://cdn.rawgit.com/fuhrmanator/GIFT-grammar-PEG.js/master/GIFT.pegjs

Is this normal? 

I was looking for a way to link to a RR diagram of my grammar from my readme (ideally even show the diagram there). I know it worked some years ago. Cheers!

**Comment by dundalek** [comment]
Hey, thanks for the report. The switch to rawgit was an intentional feature. If I remember correctly using raw.githubcontent.com did not work well in the past, therefore we were replacing it with rawgit. But now rawgit has shut down, so that stopped working.

But it seems raw.githubcontent.com works now, so I removed the replacement logic.

Could you try out if it works for you now?

**Comment by fuhrmanator** [comment]
Working for me! Thanks!
